name: Publish Test Report

on:
  push:
    branches:
      - main
  workflow_dispatch: # Enable manual triggering

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      - name: Copy Allure report to gh-pages branch
        run: |
          cp -r allure-report/* .
          git checkout gh-pages
          cp -r ../allure-report/* .
          git add .
          git commit -m "Publish Allure report"
          git push origin gh-pages
