name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Enable manual triggering
    inputs:
      browser:
        description: 'Choose browser (chromium, msedge)'
        required: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - run: dotnet build
      - name: Ensure browsers are installed
        run: pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
      - name: Run your tests based on chosen browser
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            if [ "${{ github.event.inputs.browser }}" == "chromium" ]; then
              dotnet test --settings chromium.runsettings
            elif [ "${{ github.event.inputs.browser }}" == "msedge" ]; then
              dotnet test --settings msedge.runsettings
            fi
          else
            # Default to Chromium if not manually triggered
            dotnet test --settings chromium.runsettings
          fi
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: bin/Debug/net8.0/playwright-traces
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          fetch-depth: 0
      - name: Copy Allure results to gh-pages branch
        run: |
          mkdir -p allure-results
          cp -r allure-results/* .
      - name: Commit and push changes to gh-pages
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add allure-report/*
          git commit -m "Add Allure report artifacts"
          git push origin gh-pages
