name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Enable manual triggering
    inputs:
      browser:
        description: 'Choose browser (chromium, msedge)'
        required: true
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - run: dotnet build
      - name: Ensure browsers are installed
        run: pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
      - name: Run your tests
        run: |
          if [ "${{ github.event.inputs.browser }}" == "chromium" ]; then
            dotnet test --settings chromium.runsettings
          elif [ "${{ github.event.inputs.browser }}" == "msedge" ]; then
            dotnet test --settings msedge.runsettings
          fi
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: bin/Debug/net8.0/playwright-traces
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results
